// apps/dashboard-svelte/src/lib/components/header.svelte
<script lang="ts">
  import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbSeparator,
    SidebarTrigger,
  } from '@pack/design-system-svelte'
  import LanguageSelector from './language-selector.svelte'
  import type { Snippet } from 'svelte'

  interface Props {
    pages?: string[]
    page: string
    children?: Snippet
  }

  let { pages = [], page, children }: Props = $props()
</script>

<header class="flex h-16 shrink-0 items-center gap-2 border-b px-4" data-slot="header">
  <SidebarTrigger class="-ml-1" />

  <div class="mx-2 h-4 w-px bg-border" role="separator" aria-orientation="vertical"></div>

  <Breadcrumb class="flex-1">
    {#each pages as p, i (i)}
      <BreadcrumbItem href="#">{p}</BreadcrumbItem>
      <BreadcrumbSeparator />
    {/each}
    <BreadcrumbItem current>{page}</BreadcrumbItem>
  </Breadcrumb>

  <div class="ml-auto flex items-center gap-2">
    <LanguageSelector />
    {@render children?.()}
  </div>
</header>

// apps/app/app/[locale]/(authenticated)/components/header.tsx
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@pack/design-system/components/ui/base-breadcrumb';
import { Separator } from '@pack/design-system/components/ui/base-separator';
import { SidebarTrigger } from '@pack/design-system/components/ui/sidebar';
import { Fragment, type ReactNode } from 'react';
import { LanguageSelector } from '@/components/language-selector';

type HeaderProps = {
  pages: string[];
  page: string;
  children?: ReactNode;
};

export const Header = ({ pages, page, children }: HeaderProps) => (
  <header className="flex h-16 shrink-0 items-center justify-between gap-2">
    <div className="flex items-center gap-2 px-4">
      <SidebarTrigger className="-ml-1" />
      <Separator orientation="vertical" className="mr-2 h-4" />
      <Breadcrumb>
        <BreadcrumbList>
          {pages.map((page, index) => (
            <Fragment key={page}>
              {index > 0 && <BreadcrumbSeparator className="hidden md:block" />}
              <BreadcrumbItem className="hidden md:block">
                <BreadcrumbLink href="#">{page}</BreadcrumbLink>
              </BreadcrumbItem>
            </Fragment>
          ))}
          <BreadcrumbSeparator className="hidden md:block" />
          <BreadcrumbItem>
            <BreadcrumbPage>{page}</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
    </div>
    <div className="flex items-center gap-2 px-4">
      <LanguageSelector />
      {children}
    </div>
  </header>
);
