// apps/dashboard-svelte/src/lib/components/sidebar/user-avatar.svelte
<script lang="ts">
import { authClient } from '@pack/auth/client.svelte';
import * as DropdownMenu from '@pack/design-system-sv/components/ui/dropdown-menu';
import { genericAvatar } from '@pack/design-system-sv/lib/utils';
import { EllipsisVertical, LogOut, Moon, Sun, User } from 'lucide-svelte';
import { mode, toggleMode } from 'mode-watcher';
import { goto } from '$app/navigation';
import { page } from '$app/state';
import { useLocale, useTranslation } from '$lib/i18n/context.svelte';

const locale = useLocale();
const t = useTranslation();

const user = $derived(page.data.user);

const avatarSrc = $derived(
  user?.image ?? genericAvatar(user?.name ?? user?.email ?? 'U')
);

async function handleSignOut() {
  await authClient.signOut();
  goto(`/${locale}/sign-in`);
}

const btnClass =
  'peer/menu-button flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm ' +
  'outline-none ring-sidebar-ring transition-[width,height,padding] ' +
  'hover:bg-sidebar-accent hover:text-sidebar-accent-foreground ' +
  'focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground ' +
  'disabled:pointer-events-none disabled:opacity-50 ' +
  'data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground';
</script>

{#if user}
    <DropdownMenu.Root>
        <DropdownMenu.Trigger>
            {#snippet child({ props })}
                <button type="button" {...props} class={btnClass}>
                    <img
                        src={avatarSrc}
                        alt={user?.name}
                        class="size-8 shrink-0 rounded-full object-cover"
                    />
                    <div
                        class="grid min-w-0 flex-1 text-left text-sm leading-tight"
                    >
                        <span class="truncate font-medium">{user?.name}</span>
                    </div>
                    <div
                        class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-sidebar-accent/50"
                    >
                        <EllipsisVertical class="size-4 opacity-40" />
                    </div>
                </button>
            {/snippet}
        </DropdownMenu.Trigger>

        <DropdownMenu.Content
            side="right"
            align="end"
            sideOffset={4}
            class="min-w-56 rounded-lg border bg-popover p-1 text-popover-foreground shadow-md"
        >
            <DropdownMenu.Item
                class="flex cursor-pointer items-center gap-3 rounded-sm px-2 py-1.5 text-sm outline-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground"
                onclick={toggleMode}
            >
                {#if mode.current === "light"}
                    <Moon class="size-4 text-muted-foreground/70" />
                {:else}
                    <Sun class="size-4 text-muted-foreground/70" />
                {/if}
                <span>{t.app.sidebar.changeTheme}</span>
            </DropdownMenu.Item>

            <DropdownMenu.Item
                class="flex cursor-pointer items-center gap-3 rounded-sm px-2 py-1.5 text-sm outline-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground"
                onclick={() => goto(`/${locale}/profile`)}
            >
                <User class="size-4 text-muted-foreground/70" />
                <span>{t.app.sidebar.profile}</span>
            </DropdownMenu.Item>

            <DropdownMenu.Separator class="my-1 h-px bg-border" />

            <DropdownMenu.Item
                class="flex cursor-pointer items-center gap-3 rounded-sm px-2 py-1.5 text-sm outline-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground"
                onclick={handleSignOut}
            >
                <LogOut class="size-4 text-destructive/70" />
                <span class="text-destructive/70">{t.app.common.logout}</span>
            </DropdownMenu.Item>
        </DropdownMenu.Content>
    </DropdownMenu.Root>
{/if}

// apps/app/components/sidebar/user-avatar.tsx
'use client';

import {
  Avatar,
  AvatarFallback,
  AvatarImage
} from '@pack/design-system/components/ui/base-avatar';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPositioner,
  DropdownMenuTrigger,
} from '@pack/design-system/components/ui/dropdown-menu';
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from '@pack/design-system/components/ui/sidebar';
import { getInitials } from '@pack/design-system/utils/formatters'
import { generateURLDiceBearAvatar } from '@pack/design-system/utils/others'
import { EllipsisVertical, LogOut, Moon, Sun, User } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useTheme } from 'next-themes';
import { authClient } from '@/lib/auth';
import { useTranslation, useLocale } from '@/lib/i18n';

export function UserAvatar() {
  const router = useRouter();
  const { isMobile } = useSidebar();
  const { theme, setTheme } = useTheme();
  const { data, isPending } = authClient.useSession();
  const t = useTranslation();
  const locale = useLocale();
  const userData = data?.user;

  const avatarSrc = userData?.image
    ? userData.image
    : generateURLDiceBearAvatar(userData?.email);

  if (isPending) {
    return (
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton
            size="lg"
            className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            disabled
          >
            <Avatar className="in-data-[state=expanded]:size-6 transition-[width,height] duration-200 ease-in-out">
              <AvatarFallback className="animate-pulse bg-muted-foreground/30"></AvatarFallback>
            </Avatar>
            <div className="ms-2 flex-1 animate-pulse text-left text-sm leading-tight">
              <span className="truncate font-medium">{t.app.sidebar.loading}</span>
            </div>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    );
  }

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger render={
            <SidebarMenuButton
              size="lg"
              className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            >
              <Avatar className="in-data-[state=expanded]:size-6 transition-[width,height] duration-200 ease-in-out">
                <AvatarImage src={avatarSrc} alt={userData?.name} />
                <AvatarFallback>
                  {getInitials(data?.user?.name ?? 'GG')}
                </AvatarFallback>
              </Avatar>
              <div className="ms-1 grid flex-1 text-left text-sm leading-tight">
                <span className="truncate font-medium">{userData?.name}</span>
              </div>
              <div className="flex size-8 items-center justify-center rounded-lg bg-sidebar-accent/50 in-[[data-slot=dropdown-menu-trigger]:hover]:bg-transparent">
                <EllipsisVertical className="size-5 opacity-40" size={20} />
              </div>
            </SidebarMenuButton>
          } />
          <DropdownMenuPositioner side={isMobile ? 'bottom' : 'right'} align='end'  sideOffset={4}>
          <DropdownMenuContent
            className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg"
          >
            <DropdownMenuItem
              className="gap-3 px-1"
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            >
              {theme === 'light' ? (
                <Moon
                  size={20}
                  className="text-muted-foreground/70"
                  aria-hidden="true"
                />
              ) : (
                <Sun
                  size={20}
                  className="text-muted-foreground/70"
                  aria-hidden="true"
                />
              )}
              <span>{t.app.sidebar.changeTheme}</span>
            </DropdownMenuItem>
              <DropdownMenuItem className="px-1" render={
              <Link href={`/${locale}/perfil`} className="flex items-center gap-3">
                <User
                  size={20}
                  className="text-muted-foreground/70"
                  aria-hidden="true"
                />
                <span>{t.app.sidebar.profile}</span>
              </Link>
            }/>
            <DropdownMenuItem
              className="gap-3 px-1"
              onClick={async () => {
                await authClient.signOut({ fetchOptions: {} });
                router.push(`/${locale}/entrar`);
              }}
            >
              <LogOut
                size={20}
                className="text-destructive/70"
                aria-hidden="true"
              />
              <span className="text-destructive/70">{t.app.common.logout}</span>
            </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenuPositioner>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}
