// apps/dashboard-svelte/src/lib/components/language-selector.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { locales, addLocaleToPathname, removeLocaleFromPathname } from '@pack/i18n/utils'
  import { useLocale } from '$lib/i18n/context.svelte'

  const locale = useLocale()

  const languageNames: Record<string, string> = {
    en: '🇺🇸 English',
    es: '🇪🇸 Español',
    pt: '🇧🇷 Português',
  }

  function handleChange(event: Event) {
    const target = event.target as HTMLSelectElement
    const newLocale = target.value
    const currentPath = removeLocaleFromPathname(page.url.pathname)
    goto(addLocaleToPathname(currentPath, newLocale as typeof locales[number]))
  }
</script>

<select
  value={locale}
  onchange={handleChange}
  class="h-8 rounded-md border border-input bg-background px-2 text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
  aria-label="Select language"
>
  {#each locales as l (l)}
    <option value={l}>{languageNames[l] ?? l}</option>
  {/each}
</select>

// apps/app/components/language-selector.tsx
'use client';

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@pack/design-system/components/ui/select';
import { usePathname, useRouter } from 'next/navigation';
import { useLocale } from '@/lib/i18n/provider';
import { locales } from '@pack/i18n';
import { addLocaleToPathname, removeLocaleFromPathname } from '@/lib/i18n/utils';

const languageNames: Record<string, string> = {
  en: 'English',
  es: 'Español',
  pt: 'Português',
};

const languageFlags: Record<string, string> = {
  en: '🇺🇸',
  es: '🇪🇸',
  pt: '🇧🇷',
};

export function LanguageSelector() {
  const router = useRouter();
  const pathname = usePathname();
  const currentLocale = useLocale();

  const handleLocaleChange = (newLocale: string) => {
    const pathWithoutLocale = removeLocaleFromPathname(pathname);
    const newPath = addLocaleToPathname(pathWithoutLocale, newLocale as any);
    router.push(newPath);
  };

  return (
    <Select value={currentLocale} onValueChange={handleLocaleChange}>
      <SelectTrigger className="w-40">
        <SelectValue>
          <span className="flex items-center gap-2">
            <span>{languageFlags[currentLocale]}</span>
            <span>{languageNames[currentLocale]}</span>
          </span>
        </SelectValue>
      </SelectTrigger>
      <SelectContent>
        {locales.map((locale) => (
          <SelectItem key={locale} value={locale}>
            <span className="flex items-center gap-2">
              <span>{languageFlags[locale]}</span>
              <span>{languageNames[locale]}</span>
            </span>
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}
